import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Auth",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider
            appearance={{
                baseTheme: dark,
            }}
        >
            <html lang='en'>
                <body className={`${inter.className} bg-dark-1`}>
                    <div className="flex justify-center w-full my-auto">
                        {children}
                    </div>
                </body>
            </html>
        </ClerkProvider>
    );
}